services:
  db:
    image: postgres:alpine
    environment: { POSTGRES_PASSWORD: postgres }
    ports: [ '5432:5432' ]
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql