services:
  db:
    image: postgres:alpine
    environment: { POSTGRES_PASSWORD: postgres,  POSTGRES_USER: postgres}
    ports: [ '5432:5432' ]
    restart: always
    volumes:
      - ./schema-dev.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5