---
spring:
  pg:
    db:
      host: ${PG_HOST}
  config:
    activate:
      on-profile: default
  datasource:
    password: postgres
    url: jdbc:postgresql://${pg.db.host}:5432/gebit
    username: postgres
  liquibase:
    contexts: prod
    change-log: classpath:db/changelog/db.changelog-master-prod.yaml
  web.resources.static-locations: file:./apps/
cds:
  index-page:
    path: cap
    enabled: false
  data-source:
    auto-config:
      enabled: false
  security:
    mock:
      default-users:
        enabled: false
