---
spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/gebit
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    embedded-database-connection: none
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.yaml

cds:
  index-page:
    path: services
    enabled: false
  security:
    mock:
      enabled: false
  data-source:
    auto-config:
      enabled: false

jwt.secret.access: ${JWT_ACCESS_SECRET}
jwt.secret.refresh: ${JWT_REFRESH_SECRET}