---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    password: postgres
    url: jdbc:postgresql://${PG_HOST}:5432/gebit
    username: postgres
  liquibase:
    contexts: prod
    change-log: classpath:db/changelog/db.changelog-master-prod.yaml

cds:
  index-page:
    path: services
    enabled: false
  security:
    mock:
      enabled: false
  data-source:
    auto-config:
      enabled: false

jwt.secret.access: ${JWT_ACCESS_SECRET}
jwt.secret.refresh: ${JWT_REFRESH_SECRET}