---
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gebit_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.yaml

cds:
  index-page:
    path: services
    enabled: true
  security:
    mock:
      enabled: false
  data-source:
    auto-config:
      enabled: false

jwt.secret.access: ${JWT_ACCESS_SECRET}
jwt.secret.refresh: ${JWT_REFRESH_SECRET}

aws:
  accessKeyId:  ${DO_SPACE_KEY_ID}
  secretAccessKey: "${DO_SPACE_SECRET_KEY}"
  endpoint: ${DO_SPACE_ENDPOINT}
  region: ${DO_SPACE_REGION}
  bucket: ${DO_SPACE_BUCKET}

email:
  enabled: true
  brevo:
    api:
      url: ${BREVO_URL}
      key: ${BREVO_KEY}
    sender:
      name: ${EMAIL_SENDER}
      email: ${EMAIL}

management:
  endpoint:
    health:
      show-components: always # shows individual indicators
  endpoints:
    web:
      exposure:
        include: health # only expose /health as web endpoint
  health:
     defaults.enabled: false # turn off all indicators by default
     ping.enabled: true
     db.enabled: true

org:
  gebit:
    admins: ${SUPPORT_ADMINS}